config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'posts#index', as:'home'
  get 'new' =>  'pages#new'

  resources :posts do
   resources :comments , only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :usernames, presence: true, length: {minimum: 5}
  validates :body, presence: true, length: {minimum: 20}
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true, length: {minimum: 20}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private
   def comment_params
    params.require(:comment).permit(:username, :body)
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :load_post , only: [:show, :edit, :update, :destroy]

  def index
     @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @comment = @post.comments.build
  end

  def edit

  end

  def update
    if (@post.update(post_params))
     redirect_to @post
    else
     render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def create
    @post = Post.new(post_params)

    if @post.save
     redirect_to @post
    else
     render 'new'
    end
  end

  private

  def load_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<%= stylesheet_link_tag   'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="user_nav">
      <% if user_signed_in? %>
     Signed in as <%= current_user.email %>. Not You?
     <%= link_to "Sign out", destroy_user_session_path %>
      <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
      <% end %>
    </div>

   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Misha-blog</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <span class="p-2 text-dark"><%= link_to "Home page", home_path  %></span>

  </nav>
  <span class="btn btn-outline-primary"><%= link_to "ADD Post", new_post_path %></span>
</div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h2> Redact post</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
 <% if @post.errors.any? %>
   <% @post.errors.full_messages.each do |msg| %>
     <div class="alert alert-danger"><%= msg %></div>
   <% end %>
    <% end %>
<p>
  name<br>
   <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Post text<br>
   <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
   <%= f.submit({:class => 'btn btn-succes'}) %>
</p>
<% end %>

app/views/posts/index.html.erb
<h1> All of our posts </h1>
<% @post.each do |post| %>
 <div class="alert alert-light">
<h3><%= post.title %></h3>
<p><%= post.body %></p>
<%= link_to "read next", post_path(post), :class =>'btn btn-outline-primary' %>
</div>
<% end %>

app/views/posts/new.html.erb
<h2> Add new post</h2>
<%= form_for :post, url: posts_path do |f| %>
 <% if @post.errors.any? %>
   <% @post.errors.full_messages.each do |msg| %>
     <div class="alert alert-danger"><%= msg %></div>
   <% end %>
    <% end %>
<p>
  name<br>
   <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Post text<br>
   <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
   <%= f.submit({:class => 'btn btn-succes'}) %>
</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Redact", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "DESTROY", post_path(@post), method: :delete, data:{confirm:" do you want to destroy post?"}, :class => 'btn btn-danger' %>
<hr>
<h2> All of our posts </h2>
<% @post.comments.each do |comment| %>
 <div class="alert alert-light">
<p><strong><%= comment.username %></strong>: <%= comment.body %></p>
</div>
<% end %>
<hr>
<h2> ADD Comments</h2>
<%= form_for(@comment, url: post_comments_path(@post), method: :post) do |f| %>
<p>
  User name<br>
   <%= f.text_field(:username, {:class => 'form-control'}) %>
</p>
<p>
  Comment text<br>
   <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
   <%= f.submit("add comment",{:class => 'btn btn-warning'})%>
</p>
<%binding.pry %>
<% end %>